version: '3.1'
services:
  app:
    container_name: save-user-info-service
    image: save-user-info-service
    build: ./
    ports:
      - "8080:8080"
    depends_on:
      - postgresqldb
  postgresqldb:
    image: postgres
    build:
      context: ./
      dockerfile: Dockerfilepostgres
    ports:
      - "5432:5432"
    environment:
      - PGDATA=/var/lib/postgresql/data
      - POSTGRES_PASSWORD=javaapp
      - POSTGRES_USER=javaapp