spring:
  application:
    name: save-user-info-service
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: javaapp
    password: javaapp
    driver-class-name: org.postgresql.Driver
  jpa:
    database: postgresql
    show-sql: true
  sql:
    init:
      mode: never
  kafka:
    bootstrap-servers: localhost:29092,localhost:29093  # Адрес Kafka сервера
    consumer:
      group-id: user-info-consumer-group  # Идентификатор группы потребителей
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
