spring:
  application:
    name: 'send-user-info-service'
  kafka:
    bootstrap-servers: localhost:29092,localhost:29093  # Адрес Kafka сервера
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
  rabbitmq:
    host: localhost
    port: 5672
    username: javaapp
    password: javaapp
    virtual-host: uservh
app:
  messaging: kafka # rabbit или kafka